# Generated by Django 4.1.5 on 2023-01-30 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempthistory',
            options={'verbose_name_plural': 'Attempt History'},
        ),
        migrations.AlterModelOptions(
            name='userlist',
            options={'verbose_name_plural': 'Persons'},
        ),
    ]
